# Generated by Django 5.1.1 on 2024-10-16 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 16, 21, 38, 48, 810738)),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 16, 21, 38, 48, 810745)),
        ),
    ]
