# Generated by Django 5.1.1 on 2024-10-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishapp', '0002_alter_dishes_create_at_alter_dishes_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
