# Generated by Django 5.1.1 on 2024-10-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishapp', '0003_alter_dishes_create_at_alter_dishes_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='picture',
            field=models.ImageField(null=True, upload_to='picture/'),
        ),
    ]
