# Generated by Django 5.1.1 on 2024-10-27 04:37

import dishapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishapp', '0004_alter_dishes_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='picture',
            field=models.FileField(null=True, upload_to='picture/', validators=[dishapp.models.validate_image_file]),
        ),
    ]
