# Generated by Django 5.1.1 on 2024-10-12 01:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='users',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
