# Generated by Django 5.1.1 on 2024-10-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_users_create_at_users_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
